# Generated by Django 4.1.7 on 2023-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=0, upload_to='image_admin'),
            preserve_default=False,
        ),
    ]
